RegulaGasto/RegulaGasto.UI.Web/Controllers/GastoController.cs
using RegulaGasto.Aplicacao;
using RegulaGasto.Dominio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegulaGasto.UI.Web.Controllers
{
    public class GastoController : Controller
    {
        // GET: Gasto
        public ActionResult Index()
        {
            
           
            var appGasto = new GastoAplicacao();
            var valorTotal = appGasto.ValorTotal();
            ViewData["Total"] = valorTotal;
            var listadeGastos = appGasto.ListaTodos();           
            return View(listadeGastos);
            

        }

        public ActionResult Cadastrar()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Gasto gasto)
        {
            if (ModelState.IsValid)
            {
                var appGasto = new GastoAplicacao();
                appGasto.Salvar(gasto);
                return RedirectToAction("Index");
            }
            return View(gasto);
        }

        public ActionResult Consultar(string Categoria)
        {        
            return View();
        }

        [HttpPost, ActionName("Consultar")]
        public ActionResult ConsultarIndex(string Categoria)
        {
            var appGasto = new GastoAplicacao();
            var valortotal = appGasto.ValorTotalPorCategoria(Categoria);
            ViewData["Total"] = valortotal;
            var consulta = appGasto.ListarporCategoria(Categoria);
            if (consulta == null)
                return HttpNotFound();

            return View(consulta);
        }

        public ActionResult ListarPorMes(string Mes)
        {      
            return View();
        }

        [HttpPost, ActionName("ListarPorMes")]
        public ActionResult ListarPorMesIndex(string Mes)
        {
            var appGasto = new GastoAplicacao();
            var valorTotal = appGasto.ValorTotalPorMes(Mes);
            ViewData["Total"] = valorTotal;
            var consulta = appGasto.ListarporMes(Mes);
            if (consulta == null)
                return HttpNotFound();

            return View(consulta);
        }



        public ActionResult Editar(int id)
        {
            var appGasto = new GastoAplicacao();
            var gasto = appGasto.ListarPorId(id);
            if (gasto == null)
                return HttpNotFound();
            return View(gasto);                       
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Gasto gasto)
        {
            if (ModelState.IsValid)
            {
                var appGasto = new GastoAplicacao();
                appGasto.Salvar(gasto);
                return RedirectToAction("Index");
            }
            return View(gasto);
        }

        public ActionResult Detalhes(int id)
        {
            var appGasto = new GastoAplicacao();
            var gasto = appGasto.ListarPorId(id);
            if (gasto == null)
                return HttpNotFound();
            return View(gasto);
        }

        public ActionResult Excluir(int id)
        {
            var appGasto = new GastoAplicacao();
            var gasto = appGasto.ListarPorId(id);
            if (gasto == null)
                return HttpNotFound();
            return View(gasto);
        }
        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirConfirmar(int id)
        {
            var appGasto = new GastoAplicacao();
            appGasto.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

RegulaGasto/RegulaGasto.UI.Web/Controllers/HomeController.cs
using RegulaGasto.Aplicacao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegulaGasto.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Descrição";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Informações";

            return View();
        }
    }
}

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/Cadastrar.cshtml
@model RegulaGasto.Dominio.Gasto

@{
    ViewBag.Title = "Novo Gasto";
}

<h2>Novo Gasto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
 
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-warning" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Inserir" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/Consultar.cshtml
@model IEnumerable<RegulaGasto.Dominio.Gasto>

@{
    ViewBag.Title = "Consultar";
}

<h2>Consultar</h2>

<p>
</p>

@using (Html.BeginForm())
{
    <fieldset>
        <legend></legend>
        <div class="editor-label">
            <label>Categoria</label>
        </div>
        <div class="editor-field">
            <input type="text" name="Categoria" placeholder="Categoria" required="true" />
        </div>
        <br />
        <input type="submit" value="Consultar" />

    </fieldset>
}
@if (Model != null)
{
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Mes)
        </th>
        <th></th>
    </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Mes)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Excluir", new { id = item.Id })
                </td>
            </tr>
        }
    

</table>
}
@if (ViewData["Total"] != null)
{
    <p>Total: @ViewData["Total"]</p>

}

<div>
    @Html.ActionLink("Retornar a Lista", "Index")
</div>

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/Detalhes.cshtml
@model RegulaGasto.Dominio.Gasto

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Gasto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Retornar a Lista", "Index")
</p>

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/Editar.cshtml
@model RegulaGasto.Dominio.Gasto

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gasto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categoria, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/Excluir.cshtml
@model RegulaGasto.Dominio.Gasto

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Deseja Realmente Excluir?</h3>
<div>
    <h4>Gasto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/Index.cshtml
@model IEnumerable<RegulaGasto.Dominio.Gasto>

@{
    ViewBag.Title = "Lista De Gastos";
}

<h2>Lista de Gastos</h2>

<table class="table">
    <tr>
        <td>
            <label style="color:Brown; font-weight: bolder">Inserir Novo Gasto</label>
            <a class="img-rounded" href='@Url.Content("~/Gasto/Cadastrar")'> <img src="~/Content/Images/Button-Add-icon.png" /></a>
        </td>
        <td>
            <label style="color:Brown; font-weight: bolder">Consultar por Categoria</label>
            <a class="img-rounded" href='@Url.Content("~/Gasto/Consultar")'> <img src="~/Content/Images/Lupa-Icon.png" /></a>
            @*@Html.ActionLink("Inserir Novo Gasto", "Cadastrar",null, new { Style = "color:Brown; font-weight: bolder; background-color: Brow"}) <br/>*@
            @*@Html.ActionLink("Consultar por Categoria", "Consultar", null, new { Style = "color:Brown; font-weight: bolder; background-color: Brow" })*@
        </td>
        <td>
            <label style="color:Brown; font-weight: bolder">Listar Por Mês</label>
            <a class="img-rounded" href='@Url.Content("~/Gasto/ListarPorMes")'> <img src="~/Content/Images/Lupa-Icon.png" /></a>
        </td>
    </tr>
</table>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Mes)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Mes)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.Id })
            </td>
        </tr>
    }


</table>

@if (ViewData["Total"] != null)
{
    <p>Total: @ViewData["Total"]</p>

}

RegulaGasto/RegulaGasto.UI.Web/Views/Gasto/ListarPorMes.cshtml
@model IEnumerable<RegulaGasto.Dominio.Gasto>


@{
    ViewBag.Title = "ListarPorMes";
}

<h2>Listar Gastos Por Mês</h2>

@using (Html.BeginForm())
{
    <fieldset>
        <legend></legend>
        <div class="editor-label">
            <label>Mês</label>
        </div>
        <div class="editor-field">
            <input type="text" name="Mes" placeholder="Mês" required="true" />
        </div>
        <br />
        <input type="submit" value="Listar" />

    </fieldset>
}
@if (Model != null){
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Mes)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Mes)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.Id })
            </td>
        </tr>
    }


</table>
}

@if (ViewData["Total"] != null)
{
    <p>Total: @ViewData["Total"]</p>

}

<div>
    @Html.ActionLink("Retornar a Lista", "Index")
</div>

RegulaGasto/RegulaGasto.UI.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>O Intuito desse projeto é gerenciar os gastos</p>

RegulaGasto/RegulaGasto.UI.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Avenida ACM, Parque Bela Vista de Brotas<br />
    Cond. Candeal, Residencial Beta 1962, SSA 40280-000<br />
    <abbr title="Numero de Contato">Tel:</abbr>
    (71) 99961-3860
</address>

<address>
    <strong>Corporativo:</strong>   <a href="david.souza@imap.org.br">david.souza@imap.org.br</a><br />
    <strong>Pessoal:</strong> <a href="davidsscontato@gmail.com">davidsscontato@gmail.com</a>
</address>

RegulaGasto/RegulaGasto.UI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Home Page</h1>
    <h3>Gerenciar Gastos</h3>
    <p>@Html.ActionLink("Sobre", "About", null,new {@class = "btn btn-primary btn-lg" })</p>
</div>

RegulaGasto/RegulaGasto.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - GastoRegulator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GastoRegulator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Início", "Index", "Home")</li>*@
                    @*<li>@Html.ActionLink("Sobre", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Lista", "Index", "Gasto")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - David Souza</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>